### ISSUE TITLE
Flat is not a Function

### ISSUE THREAD

**Issue by issic** [jdtsmith/homebridge-denonmarantzavr#1]
Trying your plugin but can't make it work (running Homebridge in Docker)
```
[DenonMarantzAVR] Initializing DenonMarantzAVR platform...
[1/9/2019, 4:23:48 PM] [DenonMarantzAVR] DenonMarantzAVR Plugin Loaded - Version 0.1.2

/homebridge/node_modules/homebridge-denonmarantzavr/src/AVRAccessory.js:64
    ].flat();
      ^
TypeError: [this.getSwitchServices(...),this.getAccessoryInformationService(...)].flat is not a function
    at AVRAccessory.createServices (/homebridge/node_modules/homebridge-denonmarantzavr/src/AVRAccessory.js:64:7)
    at new AVRAccessory (/homebridge/node_modules/homebridge-denonmarantzavr/src/AVRAccessory.js:24:27)
    at config.avrs.forEach.avr (/homebridge/node_modules/homebridge-denonmarantzavr/src/index.js:24:24)
    at Array.forEach (<anonymous>)
    at AVRPlatform.accessories (/homebridge/node_modules/homebridge-denonmarantzavr/src/index.js:22:22)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Comment by jeremyabramson** [comment]
From this page: [https://stackoverflow.com/questions/50993498/flat-is-not-a-function-whats-wrong](https://stackoverflow.com/questions/50993498/flat-is-not-a-function-whats-wrong)

if you paste the function included there at the top of your homebridge-denonmarantzavr/src/AVRAccessory.js file, you should be set.  Example:

```
use strict';
var net = require('net');
var throttledQueue=require('throttled-queue');

const PORT = 23;

let Characteristic, Service;

Object.defineProperty(Array.prototype, 'flat', {
    value: function(depth = 1) {
      return this.reduce(function (flat, toFlatten) {
        return flat.concat((Array.isArray(toFlatten) && (depth-1)) ? toFlatten.flat(depth-1) : toFlatten);
      }, []);
    }
});




class AVRAccessory {
  constructor(api, log, config) {
```
** snip **

**Comment by jdtsmith** [comment]
It relies on Array.flat that came with a newer version of node.   Not sure which version but 11 works.

**Comment by jdtsmith** [comment]
This has been fixed by eliminating the use of flat(), you can try again with older node versions.

**Comment by ggoodale** [comment]
Thanks for the great plugin! When you have a moment, it'd be great to tag this 0.1.3 and push it to npm, for those of us running homebridge on devices less conducive to patching (e.g. a NAS device like Synology).

**Comment by jdtsmith** [comment]
Thanks, done.
